# Generated by Django 3.0.3 on 2020-09-30 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abort',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abort', to='backend.Queue'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete', to='backend.Queue'),
        ),
        migrations.AlterField(
            model_name='halt',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halt', to='backend.Queue'),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run', to='backend.Queue'),
        ),
        migrations.AlterField(
            model_name='success',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='success', to='backend.Run'),
        ),
    ]
